export const MODAL_BODY_TYPES = {
  USER_DETAIL: 'USER_DETAIL',
  CONFIRMATION: 'CONFIRMATION',
  USERS_ADD_NEW: 'USERS_ADD_NEW',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CANDIDATE_ADD_NEW: 'CANDIDATE_ADD_NEW',
  CANDIDATE_SCORE: 'CANDIDATE_SCORE',
  COMPETITION_ADD_NEW: 'COMPETITION_ADD_NEW',
  FINALIST_ADD: 'FINALIST_ADD',
  DEFAULT: '',
};

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  CANDIDATE_DELETE: 'CANDIDATE_DELETE',
  COMPETITION_DELETE: 'COMPETITION_DELETE',
  USERS_DELETE: 'USERS_DELETE',
  SUBMIT_FINAL: 'SUBMIT_FINAL',
  LOGOUT_USER: 'LOGOUT_USER',
  COMPETITION_STATUS_UPDATE: 'COMPETITION_STATUS_UPDATE',
};

// module.exports = Object.freeze({
//   MODAL_BODY_TYPES: {
//     USER_DETAIL: 'USER_DETAIL',
//     CONFIRMATION: 'CONFIRMATION',
//     USERS_ADD_NEW: 'USERS_ADD_NEW',
//     RESET_PASSWORD: 'RESET_PASSWORD',
//     CANDIDATE_ADD_NEW: 'CANDIDATE_ADD_NEW',
//     CANDIDATE_SCORE: 'CANDIDATE_SCORE',
//     COMPETITION_ADD_NEW: 'COMPETITION_ADD_NEW',
//     FINALIST_ADD: 'FINALIST_ADD',
//     DEFAULT: '',
//   },

//   RIGHT_DRAWER_TYPES: {
//     NOTIFICATION: 'NOTIFICATION',
//     CALENDAR_EVENTS: 'CALENDAR_EVENTS',
//   },

//   CONFIRMATION_MODAL_CLOSE_TYPES: {
//     CANDIDATE_DELETE: 'CANDIDATE_DELETE',
//     COMPETITION_DELETE: 'COMPETITION_DELETE',
//     USERS_DELETE: 'USERS_DELETE',
//     SUBMIT_FINAL: 'SUBMIT_FINAL',
//     LOGOUT_USER: 'LOGOUT_USER',
//     COMPETITION_STATUS_UPDATE: 'COMPETITION_STATUS_UPDATE',
//   },
// });
